// ui/src/components/ui/highlighted.tsx
import type * as React from 'react'
import { cn } from '@/lib/utils'

function Highlighted({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span
      data-slot="highlighted"
      className={cn('inline-block font-bold text-coollabs dark:text-warning', className)}
      {...props}
    />
  )
}

export { Highlighted }

// ui/src/lib/components/ui/highlighted/highlighted.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "$lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLSpanElement>> = $props();
</script>

<span
	bind:this={ref}
	data-slot="highlighted"
	class={cn("inline-block font-bold text-coollabs dark:text-warning", className)}
	{...restProps}
>
	{@render children?.()}
</span>
